### ISSUE TITLE
Renovate should include Gardener release note with link to GitHub release

### ISSUE THREAD

**Issue by rfranzke** [gardener/ci-infra#1734]
/kind enhancement

**What would you like to be added**:
When Renovate updates an image in `gardener/gardener` ([example](https://github.com/gardener/gardener/pull/9759)) then it should include a link to the GitHub release of the updated component, e.g. like this:

<code>
```other dependency
The `gardener/dashboard` image has been updated to `v1.75.0`. [Release Notes](https://github.com/gardener/dashboard/releases/tag/1.75.0)
```
</code>

**Why is this needed**:
Traceability

/cc @oliver-goetz 
Can we achieve this relatively simple?

**Comment by timebertt** [comment]
Maybe you can achieve this with some renovate configuration like
```json
  "prFooter": "```\nThe `{{depName}}` image has been updated to `{{newVersion}}`. ...\n```",
```
