### ISSUE TITLE
Prow adds more than two reviewers on one PR

### ISSUE THREAD

**Issue by acumino** [gardener/ci-infra#182]
/kind bug

**What happened**:
Prow adds more than two reviewers on one PR. 

**What you expected to happen**:
Prow should add only two reviewers on its own.

**How to reproduce it (as minimally and precisely as possible)**:
Create any `draft` PR prow will assign two reviewers, mark it `Ready for Review` prow again assign two more reviewers and we can mark this PR `draft` and `Ready for Review` again and again and every time PR is marked `Ready for Review` prow adds two more reviewers. For ex- check this PR
https://github.com/gardener/gardener/pull/5752

**Comment by timebertt** [comment]
I don't see the problem TBH. This draft->ready->draft->ready cycle doesn't happen frequently.
But we can also disable `blunderbuss ` if it's too confusing.

**Comment by acumino** [comment]
> I don't see the problem TBH. This draft->ready->draft->ready cycle doesn't happen frequently. But we can also disable `blunderbuss ` if it's too confusing.

It is true that this scenario is very rare. But this can be improved as non-prio task. Rather than disabling `blunderbuss` can't we make the change that it should be triggered only once when the PR is created?

**Comment by shafeeqes** [comment]
> Prow should add only two reviewers on its own.

Can't we have the old way where `gardener-maintainers` are asked for review, rather than two random people?

**Comment by acumino** [comment]
> Can't we have the old way where `gardener-maintainers` are asked for review, rather than two random people?

I am in favor of blunderbuss as it suggests those reviewers who have the most contribution in the files that are changed in PR.

**Comment by shafeeqes** [comment]
Oh, my bad! It's not random. Then I'd vote to keep it too.

**Comment by oliver-goetz** [comment]
we might have to set `blunderbluss.request_count = 2`
if it is not set, the [logic to get the current number of reviewers](https://github.com/kubernetes/test-infra/blob/be9b33c4af0677b72246b9ec9377cfc4f9844654/prow/plugins/blunderbuss/blunderbuss.go#L222) is skipped, so the whole `max_request_count` setting does not have any effect.

I'll create a PR for it and then let's see.
